### args for rosbag2hdf5.py ###

rosbag_dir: "/root/ros2-ws/src/koch_ros2_wrapper/bags"
output_dir: "/root/lerobot/dataset/hdf5"

max_frames: 1400
DT: 0.02 # 設定時間間隔 (DT = 0.02 秒，50Hz)

camera_topics:
  cam_top: "/camera/camera_top/color/image_raw/compressed"
  cam_right: "/camera/camera_right/color/image_raw/compressed"
  cam_left: "/camera/camera_left/color/image_raw/compressed"
follower_left_topic: "/left_follower/joint_states"
follower_right_topic: "/right_follower/joint_states"
left_leader_topic: "/left_leader/joint_states"
right_leader_topic: "/right_leader/joint_states"

language: "en"