### args for rosbag2hdf5.py ###

rosbag_dir: "/root/ros2-ws/src/koch_ros2_wrapper/bags"
output_dir: "/root/lerobot/dataset/hdf5/0315-wipe"

# total time = max_frames / fps
max_frames: 420
fps: 15

# align_method
qpos_align_method: "linear"  # Options: 'linear', 'nearest'
image_align_method: "nearest"  # Options: 'optical_flow', 'nearest'

camera_topics:
  cam_top: "/camera/camera_top/color/image_raw/compressed"
  cam_right: "/camera/camera_right/color/image_raw/compressed"
  cam_left: "/camera/camera_left/color/image_raw/compressed"
  cam_first: "/camera/camera_first/color/image_raw/compressed"
  cam_far: "/camera/camera_far/color/image_raw/compressed"
  
follower_left_topic: "/left_follower/joint_states"
follower_right_topic: "/right_follower/joint_states"
left_leader_topic: "/left_leader/joint_states"
right_leader_topic: "/right_leader/joint_states"

language: "en"  # Options: 'en', 'ch'